### ISSUE TITLE
Permanently deleted files not deleted from the storage

### ISSUE THREAD

**Issue by hasanur-rahman079** [papra-hq/papra#375]
### Describe the bug

Getting permanently deleted confirmation from the UI but the files still in the main storage provider. Also, If i upload files in the main storage manually it's not syncing with the papra UI.

### What happened?

After permanently deleted from the UI, the filles still in the main storage. I tested with B2 Storage and local storage both have the issue. Also, uploaded manually in the main storage to see the syncing with the Papra UI but does not syncing.

### System information

docker, win 11 and nextjs, self hosted

### Where did you encounter the bug?

A self hosted instance

**Comment by CorentinTh** [comment]
Hi @hasanur-rahman079 
Are you using the latest version (or at least >= `v0.4`)  ? this bug has been reported in #263 and fixed in #266
I've tested with `ghcr.io/papra-hq/papra:latest-rootless` (0.6.3) it works as expected

**Comment by CorentinTh** [comment]
Any news on this @hasanur-rahman079 ?

**Comment by javedh-dev** [comment]
@CorentinTh I am using `papra:latest-root` With s3 storage. I am seeing the permanently deleted files still persisted in s3 bucket.

**Comment by callmenoodles** [comment]
@CorentinTh
After permanently deleting a document, the logs only return status 200 and the file is deleted from Papra. However, it still exists on the filesystem and after restarting Papra, the file is reimported again from the ingestion folder. (I have polling enabled every 2000 ms)

**Version:** v26.2.2-rootless
**TrueNAS Version:** v1.1.5
